### ISSUE TITLE
MongoDB plugin authentication username not found

### ISSUE THREAD

**Issue by ghost** [emqx/emqx-auth-mongo#25]
Bellow is the error.log output after I try to cennect a client using the mongoDB plugin.

`2016-11-20 01:02:59.441 [error] <0.3572.0>@emqttd_protocol:process:180 Client(clientid@127.0.0.1:50074): Username 'root' login failed for notfound
2016-11-20 01:02:59.452 [error] <0.3573.0>@emqttd_protocol:process:180 Client(clientid@127.0.0.1:50076): Username 'root' login failed for notfound`

My `mqtt_user` colection is

`{
	"_id" : ObjectId("5830d95ce395a5354ef61783"),
	"username" : "root",
	"password" : "root",
	"is_superuser" : false,
	"created" : "2016.11.20 12:59:40"
}
`
and my `mqtt_acl`

`{
	"_id" : ObjectId("5830d6e8e395a534071acc14"),
	"username" : "root",
	"clientid" : "clientid",
	"pubsub" : "#"
}`

for the config I used password hash as `sha256` at first and then I tried `plain`

**Comment by arihantdaga** [comment]
@sduduzog I think this issue is duplicate with #20 . But this issue is fixed in latest build. Try once with building from latest source. Try using this http://emqtt.io/docs/v2/install.html#installing-from-source . 
I had the same issue, it was resolved after building it again. But another issue i faced was, @emqplus sha256 doesn't work. only plain is working. I kept sha256 hash of my password in password field of mongo document, it was giving me password error. later i replaced sha256 with plain and also changed my password to plain in mongo document. and it worked fine.

**Comment by turtleDeng** [comment]
@arihantdaga  
sha256
1. db.mqtt_user.insert({username: "test1", password: "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92", is_superuser: false})

2. login username: test1, password: 123456

**Comment by arihantdaga** [comment]
@turtleDeng  Yeah, it works fine. Thank you.I think i was doing some mistake.

**Comment by sduduzog** [comment]
I know its closed now. but I built from source and the auth with mongo works. What I just want to understand now is, will clients still be able to subscribe or publish on their own or do they now rely on mongodb purely for pubsub as set on the collection `mqtt_acl`

**Comment by arihantdaga** [comment]
@sduduzog  If you have enabled this plugin then clients now rely on mongodb mqtt_acl collection. if something is not found for authenticated user in the mqtt_acl then the client won't be able to do pubsub.

**Comment by mkj-git** [comment]
@arihantdaga can you explain what mistake you was doing and how you made it to working. I am also having Paho java client issue with mongodb authentication

i am getting this exception

```
Bad user name or password (4)
at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:885)
at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
at java.lang.Thread.run(Thread.java:745)
```

emqt console

```
06:47:36.456 [error] Client(notification_subs_bot@127.0.0.1:50741): Username 'undefined' login failed for username_or_password_undefined
06:47:36.463 [error] Client(notification_subs_bot@127.0.0.1:50742): Username 'undefined' login failed for username_or_password_undefined
```

**Comment by arihantdaga** [comment]
@mkj-git . From Your emqtt console- What i am seeing is "Username 'undefined'". You should check  form the paho java client itself if you are sending the right username and password, because it's sending username as undefined. 
I was having issue which said in console- Username 'myusername' login failed. But that was resolved once after rebuilding emqttd  from source.  Try using this http://emqtt.io/docs/v2/install.html#installing-from-source .

**Comment by terry-xiaoyu** [comment]
seems that the issue could be closed
